package com.example.widget

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import androidx.compose.ui.unit.dp
import androidx.test.core.app.ApplicationProvider
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class MusicWidgetTest {

    private lateinit var context: Context

    @Before
    fun setup() {
        context = ApplicationProvider.getApplicationContext()
    }

    @Test
    fun `default widget state when empty`() {
        // Clear prefs
        context.getSharedPreferences("musicpro_widget_prefs", Context.MODE_PRIVATE).edit().clear().commit()

        val state = MusicWidgetState.load(context)
        assertEquals("Aucune lecture", state.title)
        assertEquals("MusicPro", state.artist)
        assertFalse(state.isPlaying)
        assertNull(state.albumArtUri)
        assertEquals(-1L, state.trackId)
    }

    @Test
    fun `save and reload widget state with track info`() {
        MusicWidgetState.save(
            context = context,
            title = "Cyberpunk Symphony",
            artist = "Neon Dreamer",
            album = "Future Wave",
            isPlaying = true,
            albumArtUri = "content://media/external/audio/albumart/42",
            trackId = 42L
        )

        val state = MusicWidgetState.load(context)
        assertEquals("Cyberpunk Symphony", state.title)
        assertEquals("Neon Dreamer", state.artist)
        assertEquals("Future Wave", state.album)
        assertTrue(state.isPlaying)
        assertEquals("content://media/external/audio/albumart/42", state.albumArtUri)
        assertEquals(42L, state.trackId)
    }

    @Test
    fun `save and load art bitmap in widget state`() {
        val testBitmap = Bitmap.createBitmap(32, 32, Bitmap.Config.ARGB_8888)

        MusicWidgetState.save(
            context = context,
            title = "Song with art",
            artist = "Artist",
            album = "Album",
            isPlaying = false,
            albumArtUri = "content://some/art",
            trackId = 99L,
            artBitmap = testBitmap
        )

        val loadedBitmap = MusicWidgetState.loadBitmap(context)
        assertNotNull(loadedBitmap)
        assertEquals(32, loadedBitmap?.width)
        assertEquals(32, loadedBitmap?.height)
    }

    @Test
    fun `verify small and medium sizes defined in widget`() {
        val small = MusicGlanceWidget.SMALL_SIZE
        val medium = MusicGlanceWidget.MEDIUM_SIZE

        assertEquals(110.dp, small.width)
        assertEquals(90.dp, small.height)

        assertEquals(240.dp, medium.width)
        assertEquals(90.dp, medium.height)

        // Threshold check: width < 220dp corresponds to small layout
        assertTrue(small.width < 220.dp)
        assertFalse(medium.width < 220.dp)
    }

    @Test
    fun `verify intent actions generated by receiver helper`() {
        val playPauseIntent = MusicWidgetReceiver.createPlayPauseIntent(context)
        assertEquals(MusicWidgetReceiver.ACTION_PLAY_PAUSE, playPauseIntent.action)

        val nextIntent = MusicWidgetReceiver.createNextIntent(context)
        assertEquals(MusicWidgetReceiver.ACTION_NEXT, nextIntent.action)

        val prevIntent = MusicWidgetReceiver.createPrevIntent(context)
        assertEquals(MusicWidgetReceiver.ACTION_PREV, prevIntent.action)

        val updateIntent = MusicWidgetReceiver.createUpdateIntent(context)
        assertEquals(MusicWidgetReceiver.ACTION_UPDATE_STATE, updateIntent.action)
    }

    @Test
    fun `receiver handles play pause action toggle state`() {
        MusicWidgetState.save(
            context = context,
            title = "Test Song",
            artist = "Test Artist",
            album = "Test Album",
            isPlaying = false,
            albumArtUri = null,
            trackId = 1L
        )

        val receiver = MusicWidgetReceiver()
        val intent = Intent(MusicWidgetReceiver.ACTION_PLAY_PAUSE)
        receiver.onReceive(context, intent)

        // Optimistic toggle should set isPlaying to true
        val state = MusicWidgetState.load(context)
        assertTrue(state.isPlaying)
    }
}
